import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

browser = webdriver.Chrome()
browser.get("https://instagram.com")
accept_button = browser.find_element_by_xpath("/html/body/div[2]/div/div/div/div[2]/button[1]")
accept_button.click()
email = browser.find_element_by_xpath("/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[1]/div/label/input")
email.send_keys("boris@krusteff.com")
password = browser.find_element_by_xpath("/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[2]/div/label/input")
password.send_keys("bingo1312")
login_button = browser.find_element_by_xpath("/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[3]")
login_button.click()
time.sleep(5)
no_button = browser.find_element_by_xpath("/html/body/div[1]/section/main/div/div/div/div/button")
no_button.click()
time.sleep(5)
no2_button = browser.find_element_by_xpath("/html/body/div[4]/div/div/div/div[3]/button[2]")
no2_button.click()
browser.get("https://www.instagram.com/alex_3618/")
time.sleep(5)
message_button = browser.find_element_by_xpath("/html/body/div[1]/section/main/div/header/section/div[1]/div[1]/div/div[1]/div/button")
message_button.click()
time.sleep(3)
message_area = browser.find_element_by_xpath("/html/body/div[1]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea")
message_area.send_keys("Zdrasti aleks tova e bot2 programa za pisane kvo shte kajesh")
message_area.send_keys(Keys.ENTER)
time.sleep(2)
browser.close()
